// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: connection.sql

package sqlc

import (
	"context"
)

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections WHERE remote_addr = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, remoteAddr string) error {
	_, err := q.db.ExecContext(ctx, deleteConnection, remoteAddr)
	return err
}

const insertConnection = `-- name: InsertConnection :exec
INSERT INTO connections (
    remote_addr
) VALUES (
    $1
)
`

func (q *Queries) InsertConnection(ctx context.Context, remoteAddr string) error {
	_, err := q.db.ExecContext(ctx, insertConnection, remoteAddr)
	return err
}
