// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteConnection(ctx context.Context, remoteAddr string) error
	InsertConnection(ctx context.Context, remoteAddr string) error
}

var _ Querier = (*Queries)(nil)
